name: "CI"

on:
  pull_request:
    branches:
      - main
      - v**

  push:
    branches:
      - main
      - v**
    tags:
      - v*

jobs:
  # General init section to setup global variables e.g., compiler version, test os
  build-and-test:
    # Workaround for environment variables as workflow parameters: https://github.com/orgs/community/discussions/26671
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.TEST_ROLE }}
          aws-region: eu-central-1
          role-session-name: fwoa-test-workflow

      - name: Run unit tests
        run: cd deployment && chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
